title: Rafael Gonzalez Gouveia # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Científico de datos 
  <br><br>
  Matemático con máster en estadística 
  <br><br>
  <a href="https://www.linkedin.com/in/gonzalezgouveia/">Entra a mi perfil de LinkedIn</a> 
  
  <br><br>
  <a href="https://www.twitter.com/gonzalezGouveia/">Entra a mi perfil de Medium</a> 
  
  <br><br>
  <a href="https://www.medium.com/@gonzalezgouveia">Entra a mi perfil de Twitter</a> 
  
theme: jekyll-theme-minimal
